export const AWS_SPEECH_CAPABILITIES = Object.freeze({
  provider: 'aws-speech',
  allocationUnit: 'AU-046',
  operations: Object.freeze([
    'transcribe',
    'streamTranscription',
    'startTranscriptionJob',
    'getTranscriptionJob',
    'listTranscriptionJobs',
    'deleteTranscriptionJob',
    'synthesizeSpeech',
    'startSpeechSynthesisTask',
    'getSpeechSynthesisTask',
    'listSpeechSynthesisTasks',
    'describeVoices',
    'listLexicons',
    'getLexicon',
  ]),
  transcribe: Object.freeze({
    synchronous: Object.freeze({
      providerNativeMode: 'streaming',
      nativeOperation: 'StartStreamTranscription',
      adapter: 'finite-stream',
    }),
    streamingProtocols: Object.freeze(['http2', 'websocket']),
    batchStates: Object.freeze(['QUEUED', 'IN_PROGRESS', 'FAILED', 'COMPLETED']),
    batchMediaFormats: Object.freeze(['amr', 'flac', 'm4a', 'mp3', 'mp4', 'ogg', 'webm', 'wav']),
    batchMaxAudioSeconds: 28_800,
    batchMaxAudioSizeGb: 2,
    streamingMediaEncodings: Object.freeze(['pcm', 'ogg-opus', 'flac']),
    serviceManagedUriTtlMinutes: 15,
  }),
  polly: Object.freeze({
    engines: Object.freeze(['standard', 'neural', 'long-form', 'generative']),
    outputFormats: Object.freeze(['json', 'mp3', 'ogg_opus', 'ogg_vorbis', 'pcm', 'mulaw', 'alaw']),
    taskStates: Object.freeze(['scheduled', 'inProgress', 'completed', 'failed']),
    taskRecordRetentionHours: 72,
    synchronousMaxOutputMinutes: 10,
  }),
  unsupportedOperations: Object.freeze([
    'cancelTranscriptionJob',
    'cancelSpeechSynthesisTask',
    'deleteSpeechSynthesisTask',
  ]),
});
